### ISSUE TITLE
Can't find any version history, or why there was major version bump

### ISSUE THREAD

**Issue by ziaulrehman40** [curtis/honeypot-captcha#37]
**Is your feature request related to a problem? Please describe.**
We are in a process to revive an old rails 3 app to latest stack, so we are going through to update all gems and replace which needs replacement for this.
In this gem, i was looking for `history.md` or at-least release notes of some sort. I understand there has been very low activity on this and it got release 1.0 after almost 9 years of no release.

We are on v 0.x, we would like to have some reference on why there is major version bump and if there is anything we need to change. Or if this drops support for any older ruby/rails versions etc which we should be aware of.

**Describe the solution you'd like**
A `history.md` file with any major changes mentioned. And mention supported ruby+rails versions in readme. And follow this for future releases.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by curtis** [comment]
@ziaulrehman40 thanks for your questions! 

Yes, currently there is no `history.md`, but you're welcome to submit a pull request to help other users. Otherwise, take a look at the commit history to see exactly what was changed.

It's been a while since I looked at it, but I believe 1.0 incorporated several PRs, updated gems/tests/documentation, and added support for Rails 5. It should still be compatible with Rails going back to 2.3.8, as specified in the README.

I don't remember my exact thoughts at the time, but probably the only reason I cut a 1.0 was that it has been around a while, supports multiple versions of Rails, and it seemed like it was time for a true version 1.

If you find any discrepancies or issues, please open a ticket. Pull requests are always welcome. And thanks for using this gem!
